config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get '/about' => 'pages#about'
  get '/tasks' => 'pages#tasks'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about;
    end
    
    def tasks;
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


	<!-- navbar -->
	  <nav class="navbar navbar-inverse">
	    <div class="container-fluid">
  	    <!-- Brand and toggle get grouped for better mobile display -->
  	    <div class="navbar-header">
  	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
  	        <span class="sr-only">Toggle navigation</span>
  	        <span class="icon-bar"></span>
  	        <span class="icon-bar"></span>
  	        <span class="icon-bar"></span>
  	      </button>
  	      <%= link_to 'Home', root_path, class: 'navbar-brand' %><span class="glyphicon glyphicon-cutlery"> FeedYourPets.com</span></a>
  	    </div>
  
  	    <!-- Collect the nav links, forms, and other content for toggling -->
  	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
  	      <ul class="nav navbar-nav">
  	        <li class="active"><%= link_to 'Home', root_path, class: 'navbar-brand' %><span class="sr-only"></span></a></li>
  	        <li><%= link_to 'About', about_path %></a></li>
  
  	        <li class="dropdown">
  	          <%= link_to 'Tasks', tasks_path %> Tasks <span class="caret"></span></a>
  	          <ul class="dropdown-menu">
  	            <li><a href="task.html">Feed the cat</a></li>
  	            <li><a href="task.html">Feed the dog</a></li>
  	            <li><a href="task.html">Feed the platypus</a></li>
  	          </ul>
  	        </li>
  	      </ul>
  
  	      <ul class="nav navbar-nav navbar-right">
  	      </ul>


	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>
	
<div class="container">
	
<%= yield %>


</div> <!-- container -->


</body>
</html>

app/views/pages/about.html.erb
       <div class="row">
            <div class="col-xs-12">
                <ol class="breadcrumb">
					<li><a href="index.html">Home</a></li>
					<li class="active">About</li>
				</ol>
            </div>
        </div>


	<div class="row">
		<div class="col-xs-12">
			<h3>Our mission</h3>
			<p>Well, then, i confess, it is my intention to commandeer one of these ships, pick up a crew in tortuga, raid, pillage, plunder and otherwise pilfer my weasely black guts out. you're only supposed to blow the bloody doors off! when i get back, remind to tell you about the time i took 100 nuns to nairobi! at this point, i'd set you up with a chimpanzee if it'd brought you back to the world! i want to shoot the pigeons... off my roof. a drug person can learn to cope with things like seeing their dead grandmother crawling up their leg with a knife in her teeth. but no one should be asked to handle this trip. well, then, i confess, it is my intention to commandeer one of these ships, pick up a crew in tortuga, raid, pillage, plunder and otherwise pilfer my weasely black guts out.</p>
		</div>
	</div>

		<div class="row">
			<div class="col-xs-12">
				<h3>Our History</h3>
				<p>My lord! you're a tripod. we are very much alike, you and i, i and you... us. do you like my meadow? try some of my grass! please have a blade, please do, it's so delectable and so darn good looking! it's not the size mate, it's how you use it. what? no. we can't stop here. this is bat country. we're not sheep! a drug person can learn to cope with things like seeing their dead grandmother crawling up their leg with a knife in her teeth. but no one should be asked to handle this trip. we're not sheep!</p>
		</div>
	</div>

app/views/pages/home.html.erb
 <div class="row">
        <div class="col-xs-12">
            <div id="mycarousel" class="carousel slide" data-ride="carousel">

			<div class="carousel-inner" role="listbox">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#mycarousel" data-slide-to="0" class="active"></li>
                    <li data-target="#mycarousel" data-slide-to="1"></li>
                    <li data-target="#mycarousel" data-slide-to="2"></li>
                </ol>
                <!-- Wrapper for slides -->

                    <div class="item">
                        <img class="img-responsive center-block" src="kurki.png" alt="hens">

                        <div class="carousel-caption">
                            <h2>Feeding your animals since 1994.
                            </h2>

                            <p>We will help you feed everything you want.</p>
                        </div>
                    </div>
                    <div class="item active">
                        <img class="img-responsive" src="assets/images/kotki1.png" alt="cats">

                        <div class="carousel-caption">
                            <h2>Get organized.</h2>

                            <p>Don't let your kitten wait.</p>

                        </div>
                    </div>
                    <div class="item">
                        <img class="img-responsive" src="pigs1cut.png" alt="piglets">

                        <div class="carousel-caption">
                            <h2>Too many pets on your head?</h2>

                            <p>No problem! We'll take care of that.</p></p>

                        </div>
                    </div>

            </div>
                <!-- Controls -->
                <a class="left carousel-control" href="#mycarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#mycarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
</div>


<div class="row">
	<div class="col-xs-12">
		<div class="panel panel-info">
		  <!-- Default panel contents -->
		  <div class="panel-heading"><h4>Tasks to do:</h4></div>

		  <!-- List group -->
		  <ul class="list-group">
		    <a href="task.html"><li class="list-group-item">Feed the cat</li></a>
		    <a href="task.html"><li class="list-group-item">Feed the dog</li></a>
		    <a href="task.html"><li class="list-group-item">Feed the platypus</li></a>

		  </ul>
		</div>
	</div>
</div>

app/views/pages/tasks.html.erb
<div class="row">
		<div class="media">
			<div class="col-xs-8">
				<div class="media-body">
				<h3 class="media-heading">Feed the cat</h3>
				<p>You need to make your kitty's stomach full ASAP.</p>
				<div class="panel panel-info">
					<div class="panel-body">Person responsible: <strong>Joey</strong></div>
				</div>
				<div class="alert alert-success" role="alert">The task is <strong>finished.</strong>
				</div>
			</div>
			</div>

			<div class="col-cs-4">
				<div class="media-right">
				<img src="32H.jpg" class="media-object" width="140px" alt="hungry kitten">
			</div>
			</div>
		</div>
	</div>